# Generated by Django 4.2.2 on 2023-09-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_bb_achive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='achive',
        ),
    ]
