# Generated by Django 4.2 on 2023-09-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_archive'),
        ('bboard', '0004_remove_bb_achive'),
    ]

    operations = [
    ]
