# Generated by Django 4.2 on 2023-05-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_delete_child_delete_human_delete_icecream_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='spares',
        ),
        migrations.DeleteModel(
            name='AdvUser',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Spare',
        ),
    ]
