# Generated by Django 4.2 on 2023-09-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_merge_0004_alter_bb_archive_0004_remove_bb_achive'),
        ('bboard', '0005_remove_bb_archive_bb_picture'),
    ]

    operations = [
    ]
