# Generated by Django 4.2 on 2023-05-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_bb_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('B', 'куплю'), ('S', 'продам'), ('C', 'поменяю')], default='S', max_length=1),
        ),
    ]
