# Generated by Django 4.2.2 on 2023-08-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_alter_bb_options_alter_bb_order_with_respect_to'),
        ('testapp', '0003_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.rubric',),
        ),
    ]
