# Generated by Django 4.2.2 on 2023-08-31 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salad', '0002_newsl_delete_sl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsl',
            name='client',
        ),
    ]
